language: bash

services:
  - docker

before_install:
    - cd Gateway
    - docker build -t test .
    - docker tag test caspha17/test:$COMMIT
after_succes:
    - docker login -u caspha17 --password $dockerLogin
    - docker push caspha17/test:$COMMIT