language: bash
env:
    global:
      - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin
      - VERSION=2.${TRAVIS_BUILD_NUMBER}
      - DOCKER_LOCAL="${LOWERCASE_REPO_SLUG}:${TRAVIS_COMMIT}"


addons: 
    apt:
      packages:
        - coreutils
        - rsync
      
cache:
    directories:
      - "$HOME/google-cloud-sdk/"

jobs:
    include:
      script:
          - gcloud version || true
          - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
          - source /home/travis/google-cloud-sdk/path.bash.inc
          - gcloud version 
          - gcloud auth activate-service-account $Account --key-file <(echo $KEY1 | base64 --decode)
          - gcloud config set project test-220812
          - gcloud -q components update
          - gcloud compute ssh --zone "europe-west1-b" "bachelor" --project "test-220812" --command 'ls'
