language: bash

env:
    global:
      - VERSION=2.${TRAVIS_BUILD_NUMBER}
      - DOCKER_LOCAL="${LOWERCASE_REPO_SLUG}:${TRAVIS_COMMIT}"

services:
  - docker
before_install:
    - cd Gateway
    - docker build -t gateway .
    - docker tag gateway caspha17/gateway:${VERSION}
    - cd ..
    - cd SPA
    - docker build - t spa . 
    - docker tag spa caspha17/spa:${VERSION}
    - cd .. 
    - cd example-worker2
    - docker build -t worker2 . 
    - docker tag worker2 caspha17/worker2:${VERSION}

deploy:
    - docker login -u caspha17 --password $dockerLogin
    - docker push caspha17/gateway:${VERSION} 