language: bash
env:
    global:
      - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin
      - VERSION=2.${TRAVIS_BUILD_NUMBER}
      - DOCKER_LOCAL="${LOWERCASE_REPO_SLUG}:${TRAVIS_COMMIT}"

branches:
  only:
    - master 

addons:
    apt:
      packages:
        - coreutils
        - rsync
      
cache:
    directories:
      - "$HOME/google-cloud-sdk/"

jobs:
    include:
    - stage: Build and deploy gateway
      script:
        - cd Gateway
        - docker build -t gateway .
        - docker tag gateway caspha17/gateway:latest
        - docker login -u caspha17 --password $dockerLogin
        - docker push caspha17/gateway:latest
    - stage: Build and deploy spa
      script:
        - cd SPA
        - docker build -t spa -f prod.Dockerfile .
        - docker tag spa caspha17/spa:latest
        - docker login -u caspha17 --password $dockerLogin
        - docker push caspha17/spa:latest
    - stage: Build and deploy itemmanagerservice
      script:
        - cd ItemManagerService
        - docker build -t itemmanagerservice . 
        - docker tag itemmanagerservice caspha17/itemmanagerservice:latest
        - docker login -u caspha17 --password $dockerLogin
        - docker push caspha17/itemmanagerservice:latest 
    - stage: Build and deploy PriceCalendarService
      script:
        - cd PriceCalendarService
        - docker build -t pricecalendarservice . 
        - docker tag pricecalendarservice caspha17/pricecalendarservice:latest
        - docker login -u caspha17 --password $dockerLogin
        - docker push caspha17/pricecalendarservice:latest 
    - stage: Build and deploy proxy
      script:
        - cd proxy
        - docker build -t proxy . 
        - docker tag proxy caspha17/proxy:latest
        - docker login -u caspha17 --password $dockerLogin
        - docker push caspha17/proxy:latest 
    - stage: Build and deploy customer
      script:
        - cd CustomerManagerService
        - docker build -t customer . 
        - docker tag customer caspha17/customer:latest
        - docker login -u caspha17 --password $dockerLogin
        - docker push caspha17/customer:latest 
    - stage: Build and deploy booking
      script:
          - cd MailService
          - docker build -t mailservice . 
          - docker tag mailservice caspha17/mailservice:latest
          - docker login -u caspha17 --password $dockerLogin
          - docker push caspha17/mailservice:latest 
    - stage: Build and deploy MailService
      script:
          - cd BookingService
          - docker build -t booking . 
          - docker tag booking caspha17/booking:latest
          - docker login -u caspha17 --password $dockerLogin
          - docker push caspha17/booking:latest 
    - stage: Deploy Cloud
      script:
          - gcloud version || true
          - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
          - source /home/travis/google-cloud-sdk/path.bash.inc
          - gcloud version 
          - gcloud auth activate-service-account $Account --key-file <(echo $KEY1 | base64 --decode)
          - gcloud config set project test-220812
          - gcloud compute ssh test@bachelor --zone europe-west1-b --command 'cd Microservice-swarm/ && sudo git pull && sudo docker stack deploy --compose-file docker-compose.prod.yml bachelor'
