language: bash

env:
    global:
      - VERSION=1.${TRAVIS_BUILD_NUMBER}

services:
  - docker

before_install:
    - cd Gateway
    - docker build -t $TRAVIS_BUILD_DIR .
    - docker tag $TRAVIS_BUILD_DIR caspha17/$TRAVIS_BUILD_DIR:${VERSION}
after_succes:
    - docker login -u caspha17 --password $dockerLogin
    - docker push caspha17/$TRAVIS_BUILD_DIR:${VERSION} 