language: bash

env:
    global:
      - VERSION=1.${TRAVIS_BUILD_NUMBER}
      - DOCKER_LOCAL="${LOWERCASE_REPO_SLUG}:${TRAVIS_COMMIT}"

services:
  - docker

before_install:
    - cd Gateway
    - docker build -t test .
    - docker tag test caspha17/${PWD##*/}:${VERSION}
deploy:
    - docker login -u caspha17 --password $dockerLogin
    - docker push caspha17/${PWD##*/}:${VERSION} 