version: '3.0'

services: 
    pricecalendarservice:
        image: caspha17/pricecalendarservice:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5002
        deploy:
            mode: replicated
            replicas: 10
    itemmanagerservice:
        image: caspha17/itemmanagerservice:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5003
    gateway:
        image: caspha17/gateway:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5000
    frontend:
        image: caspha17/spa:latest
    proxy:
        image: caspha17/proxy:latest
        ports: 
            - 80:80
    redis:
        # Pull the image from Docker Hub
        image: redis