version: '3.0'

services: 
    worker2:
        build: 
            context: ./example-worker2/
        environment: 
            - ASPNETCORE_URLS=http://+:5002
    gateway:
        build: 
            context: ./Gateway/
        environment: 
            - ASPNETCORE_URLS=http://+:5000
    frontend:
        build:
            context: ./SPA/
    proxy:
        build:
            context: .
        ports: 
            - 80:80