version: '3.0'

services: 
    pricecalendarservice:
        image: caspha17/pricecalendarservice:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5002
            - RedisConnection=redis
        deploy:
            mode: replicated
            replicas: 10
        labels:
            - "com.docker.lb.hosts=demo.local"
            - "com.docker.lb.sticky_session_cookie=session" 
        depends_on: 
            - rabbitmq
    itemmanagerservice:
        image: caspha17/itemmanagerservice:latest
        deploy:
            mode: replicated
            replicas: 4
        environment: 
            - ASPNETCORE_URLS=http://+:5003
        depends_on: 
            - rabbitmq
    gateway:
        image: caspha17/gateway:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5000
    frontend:
        image: caspha17/spa:latest
    proxy:
        image: caspha17/proxy:latest
        ports: 
            - 80:80
    redis:
        # Pull the image from Docker Hub
        image: redis
        ports: 
            - 6379:6379
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        expose:
            - "5672"
            - "15672"