version: '3.0'

services: 
    pricecalendarservice:
        image: caspha17/pricecalendarservice:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5002
            - RedisConnection=redis
        deploy:
            mode: replicated
            replicas: 1
        labels:
            - "com.docker.lb.hosts=demo.local"
            - "com.docker.lb.sticky_session_cookie=session" 
    itemmanagerservice:
        image: caspha17/itemmanagerservice:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5003
    identityservice:
        image: caspha17/identity:latest
        environment: 
             - DEV_URL=http://34.77.231.255
             - ASPNETCORE_ENVIRONMENT=Developmnet
             - ASPNETCORE_URLS=http://+:5010
             - IDENTITY_ISSUER=http://34.77.231.255/auth
             - RedisConnection=redis
    gateway:
        image: caspha17/gateway:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5000
    frontend:
        image: caspha17/spa:latest
    proxy:
        image: caspha17/proxy:latest
        ports: 
            - 80:80
    redis:
        # Pull the image from Docker Hub
        image: redis
        ports: 
            - 6379:6379