version: '3.7'

services: 
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        expose:
            - "5672"
            - "15672"
    pricecalendarservice:
        build: 
            context: ./PriceCalendarService
        environment: 
            - ASPNETCORE_URLS=http://+:5002
            - RedisConnection=redis
        depends_on: 
            - rabbitmq
    gateway:
        build: 
            context: ./Gateway/
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - ID_URL=http://identityservice
            - IDENTITY_AUTHORITY="http://identityservice:5000"
    frontend:
        build:
            context: ./SPA
            dockerfile: staging.dockerfile
    itemmanagerservice: 
        build:
            ./ItemManagerService
        environment: 
            - ASPNETCORE_URLS=http://+:5003
            - IdentityUrl=http://identityservice
    customerservice: 
        depends_on:
            - mongo
        build:
            context: ./CustomerManagerService
        environment: 
            - ASPNETCORE_URLS=http://+:5004
    proxy:
        build:
            context: ./proxy
        ports: 
            - 80:80
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}./site:/data/db
            #- ./data:/data/db
        ports:
            - "27017:27017"
            
    redis:
        image: redis
        ports: 
            - 6379:6379
