version: '3.0'

services: 
    worker1:
        build:
            context: ./example_worker/
        environment: 
            - ASPNETCORE_URLS=http://+:5000
        ports: 
            - 5000:5000
    worker2:
        build: 
            context: ./example-worker2/
        environment: 
            - ASPNETCORE_URLS=http://+:5001
        ports: 
            - 5001:5001
        

