version: '3.0'

services: 
    pricecalendarservice:
        image: caspha17/pricecalendarservice:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5002
            - RedisConnection=redis
        deploy:
            mode: replicated
            replicas: 2
        labels:
            - "com.docker.lb.hosts=demo.local"
            - "com.docker.lb.sticky_session_cookie=session" 
        depends_on: 
            - rabbitmq
    itemmanagerservice:
        image: caspha17/itemmanagerservice:latest
        deploy:
            mode: replicated
            replicas: 2
        environment: 
            - ASPNETCORE_URLS=http://+:5003
        depends_on: 
            - rabbitmq
    gateway:
        image: caspha17/gateway:latest
        environment: 
            - ASPNETCORE_URLS=http://+:5000
    frontend:
        image: caspha17/spa:latest
    proxy:
        image: caspha17/proxy:latest
        ports: 
            - 80:80
    redis:
        # Pull the image from Docker Hub
        image: redis
        ports: 
            - 6379:6379
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        expose:
            - "5672"
            - "15672"
    customerservice: 
        image: caspha17/customer:latest
        depends_on:
            - mongo
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        links:
            - mongo
        environment: 
            - ASPNETCORE_URLS=http://+:5004
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data/mongo:/data/db/mongo
        ports:
            - "27018:27017"
    mailservice:
        build:
            context: ./MailService
        expose:
            - "80"        
    mongobooking:
        container_name: mongobooking
        image: mongo
        restart: always
        volumes:
            - ./data/mongo1:/data/db
        ports:
            - "27017:27017"
    bookingservice:
        image: caspha17/booking:latest
        depends_on:
            - mongobooking
            - rabbitmq
        environment: 
            - ASPNETCORE_URLS=http://+:5005
        links:
            - mongobooking
    mailservice:
        image: caspha17/mailservice:latest
