version: '3.0'

services: 
    pricecalendarservice:
        build: 
            context: ./PriceCalendarService
        environment: 
            - ASPNETCORE_URLS=http://+:5002
    gateway:
        build: 
            context: ./Gateway/
        environment: 
            - ASPNETCORE_URLS=http://+:5000
    frontend:
        build:
            context: ./SPA/
            dockerfile: Dockerfile
    itemmanagerservice: 
        build:
            ./ItemManagerService
        environment: 
            - ASPNETCORE_URLS=http://+:5003
    proxy:
        build:
            context: ./proxy
        ports: 
            - 80:80