version: '3.0'

services: 
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        expose:
            - "5672"
            - "15672"
    pricecalendarservice:
        build: 
            context: ./PriceCalendarService
        environment: 
            - ASPNETCORE_URLS=http://+:5002
            - RedisConnection=redis
        depends_on: 
            - rabbitmq
    gateway:
        build: 
            context: ./Gateway/
        environment: 
            - ASPNETCORE_URLS=http://+:5000
            - ID_URL=http://identityservice
    frontend:
        build:
            context: ./SPA
            dockerfile: staging.dockerfile
    itemmanagerservice: 
        build:
            ./ItemManagerService
        environment: 
            - ASPNETCORE_URLS=http://+:5003
            - IdentityUrl=http://identityservice
    identityservice:
        build:
            context: ./IdentityServer/IdentityServer
        environment: 
            - DEV_URL=http://localhost
            - ASPNETCORE_ENVIRONMENT=Developmnet
            - ASPNETCORE_URLS=http://+:5010
            - IDENTITY_ISSUER=http://localhost/auth
            - RedisConnection=redis
        ports: 
            - 5010:5010
    proxy:
        build:
            context: ./proxy
        ports: 
            - 80:80
    redis:
        image: redis
        ports: 
            - 6379:6379

