version: '3.0'

services: 
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        expose:
            - "5672"
            - "15672"
    pricecalendarservice:
        build: 
            context: ./PriceCalendarService
        ports:
            - "5002"
        environment: 
            - ASPNETCORE_URLS=http://+:5002
        depends_on: 
            - rabbitmq
    itemmanagerservice: 
        build:
            ./ItemManagerService
        ports:
            - "5003"
        environment: 
            - ASPNETCORE_URLS=http://+:5003
        depends_on:
            - rabbitmq