version: '3.0'

services: 
    identity:
        image: caspha17/identity:latest
        environment: 
             - ASPNETCORE_ENVIRONMENT=Developmnet
             - ASPNETCORE_URLS=http://+:5010
    proxy:
        image: caspha17/proxyidentity:latest
        ports: 
            - 80:80